### ISSUE TITLE
Update issue when moving to BC27.0

### ISSUE THREAD

**Issue by PeterConijn** [DmitryKatson/centralQ-ai#15]
When updating our SaaS sandboxes from 26.5 to 27.0, we are receiving an error and are unable to update.

Extension error:
```json
{
    ExtensionId: 98a1b34c-3b9e-445a-b39b-47b5f35b80b2,
    ExtensionName: CentralQ Chat,
    ExtensionPublisher: Katson.com Pte. Ltd.,
    ExtensionVersion: 0.1.89.0,
    PublishedAs: Global,
    Messages:
    src/Implementation/Agents/InsightsAgent/InsightsAgentOAuth2.Codeunit.al (41,111) - Error AL0133: Argument 5: cannot    convert from List of Text to Text,
    src/Implementation/Agents/InsightsAgent/InsightsAgentOAuth2.Codeunit.al (41,119) - Error AL0133: Argument 6: cannot convert from Text to var SecretText
} 
```

This is severely impacting our release cycle, since even uninstalling the app does not seem to resolve this error. Can you please provide a fix as soon as possible.?

**Comment by DmitryKatson** [comment]
@PeterConijn i've released the new version of CentralQ Chat today, compatible with BC 27.0. Please try to use it and let me know. Thanks for bringing this to me

**Comment by PeterConijn** [comment]
I cannot test it yet. Version 0.1.90.1 is on AppSource, but when I install in the 26.5 BC client I still get version 0.1.89 and I cannot yet update it through the Admin portal. Perhaps it will take some time for Microsoft to update that. I will keep you posted.

**Comment by DmitryKatson** [comment]
> I cannot test it yet. Version 0.1.90.1 is on AppSource, but when I install in the 26.5 BC client I still get version 0.1.89 and I cannot yet update it through the Admin portal. Perhaps it will take some time for Microsoft to update that. I will keep you posted.

The minimum version of BC for the 0.1.90.1 is 27.0, so i guess as it's now available in the AppSource it should be automatically installed during the BC upgrade to 27.

**Comment by DmitryKatson** [comment]
@PeterConijn  I will close this issue for now. You can always write here in case you still have difficulties.

**Comment by PeterConijn** [comment]
Unfortunately, upgrades are now failing on the internal error that is a known issue at the moment, so I cannot verify that this works yet. I did install the app (0.1.90) on an existing BC27 so the issue in the app itself seems solved. 

Thank you for your quick action, Dmitry! 👍🏻

**Comment by DmitryKatson** [comment]
> Unfortunately, upgrades are now failing on the internal error that is a known issue at the moment, so I cannot verify that this works yet. I did install the app (0.1.90) on an existing BC27 so the issue in the app itself seems solved.
> 
> Thank you for your quick action, Dmitry! 👍🏻

I did a quick test. 

1. Initial state:

- BC version: US Business Central 26.5 (Platform 26.0.40819.0 + Application 26.5.38752.40837)
- CentralQ Chat: 0.1.89.0

2. Run Upgrade task

3. Result

- BC version: US Business Central 27.0 (Platform 27.0.40503.0 + Application 27.0.38460.41085)
- CentralQ Chat: 0.1.90.1

So everything went smoothly without any additional efforts. I suggest maybe ask BC support or try update once again. Let me know how this will work
